config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :admins, only: [:show]
  resources :artists, only: [:create, :update, :destroy]
  resources :cart_items, only: [:show, :create, :destroy]
  resources :cds, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :events, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :asiatos, only: [:create, :destroy]
  end

  resources :purchase_histories, only: [:new, :create, :update]
    get  "/search" => "cds#search", as: "search"
    post "/event_search" => "events#event_search", as: "event_search"
    get "/cart_item" => "cart_items#show", as: "cart_item_buy"
    get "/admin_search" => "admins#search", as: "admin_search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
      has_many :musics ,inverse_of: :artist
      has_many :discs, through: :musics
	  has_many :performers
	  has_many :recoding_artists
	  has_many :cds, through: :recoding_artists
	  validates :artist_name, presence: true
end

app/models/asiato.rb
class Asiato < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cd
	belongs_to :user
end

app/models/cd.rb
class Cd < ApplicationRecord
	attachment :cd_image
	has_many :discs, inverse_of: :cd
	has_many :purchase_items
	has_many :cart_items
	has_many :recoding_artists
	has_many :artists, through: :recoding_artists
	accepts_nested_attributes_for :discs, allow_destroy: true
	accepts_nested_attributes_for :recoding_artists, allow_destroy: true
	validates :cd_title, presence: true
	validates :cd_genre, presence: true, length: { maximum:15 }
	validates :cd_label, presence: true, length: { maximum:25 }
	validates :cd_price, presence: true
	validates :cd_stock, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :event
	validates :comment, presence: true, length: { minimum:2, maximum:201 }
	validates :favorite_artist, presence: true
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :cd, inverse_of: :discs
	has_many :musics, inverse_of: :disc
    has_many :artists, through: :musics
	accepts_nested_attributes_for :musics, allow_destroy: true
	validates :disc_number, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
	attachment :event_image
	has_many :performers, dependent: :destroy, inverse_of: :event
	has_many :artists, through: :performers
	accepts_nested_attributes_for :performers, allow_destroy: true
	has_many :comments, dependent: :destroy
	has_many :asiatos, dependent: :destroy

  has_many :users, through: :asiatos
  has_many :users, through: :comments

	geocoded_by :event_address
  before_validation :geocode


	validates :event_title, presence: true
	validates :event_day, presence: true
	validates :event_city, presence: true
	validates :event_address, presence: true

	def favorited_by?(id)
	    asiatos.where(user_id: id).exists?
	end
end

app/models/music.rb
class Music < ApplicationRecord
	belongs_to :disc, inverse_of: :musics
	belongs_to :artist, inverse_of: :musics
	validates :music_title, presence: true, length: { maximum:50 }
	validates :music_number, presence: true
end

app/models/performer.rb
class Performer < ApplicationRecord
	belongs_to :artist
	belongs_to :event
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
	belongs_to :user
	has_many :purchase_items
	accepts_nested_attributes_for :purchase_items, allow_destroy: true
	validates :send_address, presence: true
	validates :send_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
	validates :send_postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "ハイフンなしの数字7桁で入力してください" }
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
	attachment :purchase_cd_image
	belongs_to :purchase_history
	belongs_to :cd
end

app/models/recoding_artist.rb
class RecodingArtist < ApplicationRecord
	belongs_to :artist
	belongs_to :cd
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attachment :user_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:trackable, :validatable

  has_many :asiatos, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :cart_items, dependent: :destroy

  has_many :purchase_historys

  has_many :events, through: :asiatos
  has_many :events, through: :comments



  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
  validates :kana_first_name, presence: true, format: { with: /\A[ァ-ンー－]+\z/, message: "全角カタカナで入力してください" }
  validates :kana_last_name, presence: true, format: { with: /\A[ァ-ンー－]+\z/, message: "全角カタカナで入力してください" }
  validates :nick_name, presence: true, length: { maximum:12 }
  validates :email, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "ハイフンなしの数字7桁で入力してください" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\zA|\A\d{11}\z/, message: "ハイフンなしの11桁で入力してください" }

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/asiatos_helper.rb
module AsiatosHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_disc_fields.erb
<div class="nested-fields">
	<div>
		<%= f.label :Disc %>
		<%= f.number_field :disc_number %>
	</div>
    <div>
    	<%= f.fields_for :musics do |music| %>
	    <%= render 'music_fields', f: music %>
	    <% end %>
	</div>
	<div>
		<%= link_to_add_association '曲を追加', f, :musics, class:"btn btn-default" %>
	    <%= link_to_remove_association "Discを削除", f, class:"btn btn-default" %>
    </div>
</div>

app/views/admins/_disc_fields.html.erb
<div class="nested-fields">
	<div>
		<%= f.label :Disc %>
		<%= f.number_field :disc_number %>
	</div>
    <div>
    	<%= f.fields_for :musics do |music| %>
	    <%= render 'music_fields', f: music %>
	    <% end %>
	</div>
	<div>
		<%= link_to_add_association '曲を追加', f, :musics, class:"btn btn-info" %>
	    <%= link_to_remove_association "Discを削除", f, class:"btn btn-danger" %>
    </div>
</div>

app/views/admins/_music_fields.erb
<div class="nested-fields">
	    <%= f.label :曲順 %>
		<%= f.number_field :music_number %>
		<%= f.label :曲名 %>
        <%= f.text_field :music_title %>
        	<%= f.fields_for :recording_artists do |f| %>
            <%= f.select :artist_id, @artist_names_id, :include_blank => true %>
            <% end %>
    	<%= link_to_remove_association "曲を削除", f, class:"btn btn-default" %>
</div>

app/views/admins/_music_fields.html.erb
<div class="nested-fields">
	    <%= f.label :曲順 %>
		<%= f.number_field :music_number %>
		<%= f.label :曲名 %>
        <%= f.text_field :music_title %>
        <%= f.label :アーティスト名 %>
        <%= f.select :artist_id, @artist_names_id, :include_blank => true %>
    	<%= link_to_remove_association "曲を削除", f, class:"btn btn-warning" %>
</div>

app/views/admins/_performer_fields.erb
<div class="nested-fields">
	    <%= f.label :出演アーティスト %>
	    <%= f.select :artist_id, @artist_names_id, :include_blank => true %>
    	<%= link_to_remove_association "行を削除", f, class:"btn btn-default" %>
</div>

app/views/admins/search.html.erb
<div class="contener", style="margin-top: 200px;">
  <div class="row">
    <div class="col-lg-1">

    </div>
    <div class="col-lg-10">
      <%= link_to "管理者画面に戻る", admin_path(current_user.id) ,class: "btn btn-info"%>
      <div>
        <div class="well">
          <h2>ユーザー情報</h2>
          <div>
            <div>
              <%= form_with(url: admin_search_path, method: :get, local: true) do |f| %>
              <%= f.text_field :content, :placeholder => "ニックネームを入力" %><%= f.submit "探す" %>
              <% end %>
            </div>
            <table class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>ユーザー画像</th>
                  <th>名前</th>
                  <th>編集画面</th>
                  <th>ユーザー削除</th>
                  <th>退会日時</th>
                </tr>
              </thead>
              <% @users.each do |user| %>
              <tbody>
                <tr>
                  <td><%= attachment_image_tag user, :user_image,:fill, 60, 60, format: 'jpeg', fallback: "/images/no_image.jpg", size: "60x60" %></td>
                  <td><%= user.nick_name %></td>
                  <td><%= link_to "編集画面へ", edit_user_path(user.id) %></td>
                  <td><%= link_to "削除", user_path(user.id), method: :'delete' %></td>
                  <td><%= user.deleted_at %>
                </tr>
              </tbody>
              <% end %>
            </table>
          <%= paginate @users,:param_name => 'user_page', class: "pagenate" %>
          </div>
        </div>
      </div>

      <div class="well">
        <h2>購入履歴</h2>
        <%= form_with(url: admin_search_path, method: :get, local: true) do |f| %>
        <%= f.text_field :contents, :placeholder => "ユーザー名を入力"  %><%= f.submit "探す" %>
        <% end %>
        <table class="table table-striped table-bordered table-hover">
          <thead></thead>
          <button>購入詳細</button>
          <% @userss.each do |u| %>
          <tbody>
            <tr>
              <td><%= u.user.first_name %><%= u.user.last_name %></td>
              <td><%= u.purchase_at %></td>
              <td><%= u.send_status %></td>
              <td>
                <%= form_for (u) do |f| %>
                <label><%= f.radio_button :send_status, "受注" %>受注</label>
                <label><%= f.radio_button :send_status, "商品準備中" %>商品準備中</label>
                <label><%= f.radio_button :send_status, "出荷済み" %>出荷済み</label>
                <%= f.submit "ステータスを変更" %>
                <% end %>
              <div class="slide-div">
                <p>宛名:<%= u.send_name %></p>
                <p>宛先郵便番号:<%= u.send_postal_code %></p>
                <% total_price = 0 %>
                <% u.purchase_items.each do |p| %>
                  CDタイトル<br>
                  <%= p.purchase_cd_title %><br>
                  値段:<%= p.purchase_cd_price %>円<br>
                  購入枚数:<%= p.purchase_cd_quantity %>枚<br>
                  <% total_price += p.purchase_cd_quantity * p.purchase_cd_price %><br>
                <% end %>
                <p>総計<%= total_price %>円</p>
              </div>
              </td>
          <% end %>
        </tr>
    </tbody>

  </table>
  <%= paginate @userss,:param_name => 'purchase_page',class: "pagenate" %>
</div>

<!-- CD在庫画面 -->
<div class="well">
  <h2 >CD在庫管理</h2>
    <%= form_with(url: admin_search_path, method: :get, local: true) do |f| %>
      <%= f.text_field :contentss, :placeholder => "CD名を入力" %><%= f.submit "探す" %>
    <% end %>

    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>CD名</th>
          <th>在庫数</th>
        </tr>
      </thead>
      <% @cds.each do |cd| %>
      <tbody>
        <tr>
          <td><%= cd.cd_title %></td>
          <td><%= cd.cd_stock %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
    <%= paginate @cds, :param_name => 'cd_page',class: "pagenate" %>
</div>
</div>
<div class="col-lg-1">
</div>
</div>
</div>


<style type="text/css">
.slide-div {
  width: 300px;
  text-align: center;
  margin-left: 55%;
  border: #000 1px solid;
  background-color: white;
  display: none;
}
</style>
<script type="text/javascript">
$(document).ready(function() {
  $(document).on("click", "button", function() {
    if ( $(".slide-div").css("display") == "none" ) {
      $("button").text("閉じる");
      $(".slide-div").slideDown();
    } else {
      $("button").text("購入詳細");
      $(".slide-div").slideUp();
    }
  });
});
</script>

app/views/admins/show.html.erb
<div class="adminpage" id="main" >
<div class="container">
	<div class="row">
		<div class="col-lg-1">
        </div>
		<div class="col-lg-10">
            <nav class="navbar">
            	<%= link_to "CD追加", "#1" , data: {toggle: "collapse"},class: "btn btn-primary"%>
            	<%= link_to "アーティスト追加", "#2" , data: {toggle: "collapse"},class: "btn btn-danger"%>
            	<%= link_to "イベント追加", "#3" , data: {toggle: "collapse"},class: "btn btn-warning"%>
            	<%= link_to "ユーザー情報、購入履歴、在庫一覧へ", admin_search_path ,class: "btn btn-info" %>
            	<a href="https://analytics.google.com/analytics/web/?hl=ja#/report-home/a101258708w190751070p186878085" class="btn btn-default">アクセス解析</a>
            </nav>
        </div>
		<div class="col-lg-1">
        </div>
    </div>
	<div class="row">
		<div class="col-lg-1">
        </div>
		<div class="col-lg-10">
			<div id="1" class="collapse">
			<div class="well">
			<h2>CD追加</h2>
			<%= form_for @cd do |f| %>
			    <%= f.label :CD %>
			   	<%= f.text_field :cd_title %><br>
			    <%= f.label :ジャンル %>
			    <input name="cdgenre">
			   	<%= f.select :cd_genre, @genres, :include_blank => true %><br>
                <%= f.label :レーベル名 %>
                <input name="cdlabel">
			    <%= f.select :cd_label, @labels, :include_blank => true %><br>
			    <%= f.label :値段 %>
			    <%= f.text_field :cd_price %>円<br>
			    <%= f.label :在庫数 %>
			    <%= f.number_field :cd_stock %>枚<br>
			    <%= f.label :ジャケット画像 %>
			    <%= f.attachment_field :cd_image %><br>
	            <div>
		            <%= f.fields_for :discs do |disc| %>
                        <%= render 'disc_fields', f: disc %>
                    <% end %>
                	    <%= link_to_add_association 'Discを追加', f, :discs, class:"btn btn-primary" %>
                 </div>
                <%= f.submit "CDを追加", class:"btn btn-success" %>
            <% end %>
            </div>
            </div>

            <div id="2" class="collapse well">
                <h2>アーティスト追加</h2>
                <%= form_for @artist do |i| %>
		            <%= i.text_field :artist_name %>
		            <%= i.submit "アーティストを追加", class:"btn btn-success" %>
	            <% end %>
	        </div>

            <div id="3" class="collapse well">
            <h2>イベント追加</h2>
            	<%= form_for @event do |f| %>
            	<div>
            		<%= f.label :イベント名 %>
            		<%= f.text_field :event_title %>
            	</div>
			   	<div>
			   		<%= f.label :開催日時 %>
			   		<%= f.date_field :event_day %>
			   	</div>
			   	<div>
			   		<%= f.label :開催場所画像 %>
			   		<%= f.attachment_field :event_image, placeholder: "イメージ画像を選択" %>
			   	</div>
			   	<div>
			   		<%= f.label :開催区 %>
			   		<%= f.select :event_city, [["渋谷","渋谷区"], ["新宿","新宿区"],["港","港区"]] %>
			   	</div>
			   	<div>
			   		<%= f.fields_for :performers do |performer| %>
                    <%= render 'performer_fields', f: performer %>
                    <% end %>
			   	</div>
			   	<div>
			   		<%= link_to_add_association '行を追加', f, :performers, class:"btn btn-primary" %>
			   	</div>
			   	<div>
			   		<%= f.label :MAP表示させたい位置情報の住所 %>
			   		<%= f.text_field :event_address %>
			   	</div>
			   	 <%= f.submit "イベントを追加", class:"btn btn-success" %>
                <% end %>
            </div>
		</div>
		<div class="col-lg-1">
        </div>
	</div>
</div>

<style type="text/css">
.slide-div {
  width: 150px;
  text-align: center;
  margin-left: 80%;
  border: #000 1px solid;
  display: none;
}
</style>
<script type="text/javascript">
$(document).ready(function() {
  $("button").on("click", function() {
    console.log('click')
    if ( $(".slide-div").css("display") == "none" ) {
      $("button").text("閉じる");
      $(".slide-div").slideDown();
    } else {
      $("button").text("購入詳細");
      $(".slide-div").slideUp();
    }
  });
});
</script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ashiato</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body class="back-image">
  <!-- header -->

  <header>


  <nav class=" navbar-fixed-top" style="background-color: rgba(0,0,0,0.0)">
  <div class="headerhover">
	<div class="container-fluid" >
    <div class="row">
      <div class="col-lg-2" style="color: white;">

        <% if user_signed_in?%>

          <%= link_to events_path do %>
            <%= image_tag("/images/i.png", :size => "195x195", :alt => "logo") %>
          <% end %>

        <% else %>

        <%= link_to events_path do %>
          <%= image_tag("/images/login.png", :size => "195x195", :alt => "logo") %>
        <% end %>

        <% end %>



      </div>
      <div class="col-lg-6" style=" padding-top: 50px;">

        <%= form_tag(search_path, method: :get) do %>
          <%= select_tag(:category,options_for_select([["イベント", "イベント"], ["CD", "CD"],["アーティスト", "アーティスト"]])) %>
          <%= text_field_tag(:content,'', :placeholder => "検索してください") %>
          <%= submit_tag "検索する" %>
        <% end %>


      </div>
      <div class="header col-lg-4" style="padding-top: 40px; ">
        <ul style="list-style: none; " >

                        <% if user_signed_in? && current_user.admin%>
                           <li><%=link_to "管理者画面", admin_path(current_user.id), class: "glyphicon glyphicon-cog", style: "color:white;" %></li>
                           <li><%=link_to "マイページ", user_path(current_user.id), class: "glyphicon glyphicon-user users", style: "color: white;" %></li>
                           <li>
                             <%= link_to cart_item_path(current_user.id), class: "glyphicon glyphicon-shopping-cart", style: "color: white;" do %>
                               <%= @carts.count %>
                             <% end %>
                           </li>
                           <li><%=link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout ", style: "color: white;" %></li>


                        <% elsif user_signed_in?  %>
                            <li><%=link_to "マイページ", user_path(current_user.id), class: "glyphicon glyphicon-user users",style: "color: white" %></li>
                            <li>
                              <%= link_to cart_item_path(current_user.id), class: "glyphicon glyphicon-shopping-cart", style: "color: white;" do %>
                               <%= @carts.count %>
                             <% end %>
                             </li>
                            <li><%=link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout", style: "color: white;" %></li>

                        <% else %>
                          <li><%=link_to "新規登録", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up", style: "color: white;" %></li>
                          <li><%=link_to "ログイン", new_user_session_path,  class: "glyphicon glyphicon-log-in sign_in", style: "color: white;"%></li>
                         <% end %>
        </ul>

      </div>
    </div>
    <div class="row">
      <div class="col-lg-12" style="color: white;">
        <% flash.each  do |name, msg| %>
        <strong><%= msg  %></strong>
        <% end %>
      </div>
    </div>
	</div>
</div>
</nav>
</header>

        <%= yield %>
    <footer>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">


              <%=link_to "お問合せ", "https://docs.google.com/forms/d/e/1FAIpQLSeTFTlxAC5IhX08TyNCVBe3Lp0KsBZczEEavEYUOcaM5PnmOg/viewform", class: "glyphicon glyphicon-edit sign_up", style:"color:white; padding-top: 20px; margin-left: 70%;" %>


           <h3 style="color: white; padding-left: 70%;">© 流浪IN研究会</h3>
        </div>
      </div>
    </div>
    </footer>
  </body>
</html>