config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :admins, only: [:show]
  resources :artists, only: [:create, :update, :destroy]
  resources :cart_items, only: [:show, :create, :destroy]
  resources :cds, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :events, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :asiatos, only: [:create, :destroy]
  end

  resources :purchase_histories, only: [:new, :create, :update]
    get  "/search" => "cds#search", as: "search"
    post "/event_search" => "events#event_search", as: "event_search"
    get "/cart_item" => "cart_items#show", as: "cart_item_buy"
    get "/admin_search" => "admins#search", as: "admin_search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attachment :user_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:trackable, :validatable

  has_many :asiatos, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :cart_items, dependent: :destroy

  has_many :purchase_historys

  has_many :events, through: :asiatos
  has_many :events, through: :comments



  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
  validates :kana_first_name, presence: true, format: { with: /\A[ァ-ンー－]+\z/, message: "全角カタカナで入力してください" }
  validates :kana_last_name, presence: true, format: { with: /\A[ァ-ンー－]+\z/, message: "全角カタカナで入力してください" }
  validates :nick_name, presence: true, length: { maximum:12 }
  validates :email, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "ハイフンなしの数字7桁で入力してください" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\zA|\A\d{11}\z/, message: "ハイフンなしの11桁で入力してください" }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
  def create
    if User.find_by(email: params[:user][:email])
      @user = User.find_by(email: params[:user][:email])
      if @user.deleted_at.present?
        redirect_to new_user_session_path
        flash[:danger] = "すでに退会されているユーザーです"
      else
        super
      end
    else
      super
    end
  end

  # DELETE /resource/sign_out
   def destroy
     super
   end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login

  def check_login
    redirect_to logout_path if current_user.deleted_at.present?
  end
  
  def show
    @carts = CartItem.where(user_id: current_user.id)
    @user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to events_path
    flash[:danger] = "ERROR!このページにアクセスする権限がありません。"
    end
  end

  def edit
    @carts = CartItem.where(user_id: current_user.id)
    @user = User.find(params[:id])
    if current_user.admin

    elsif @user.id != current_user.id
    flash[:danger] = "ERROR!このページにアクセスする権限がありません。"
    redirect_to events_path
    end
  end

  def update
    @user = User.find(params[:id])
    if@user.update(user_params)
      redirect_to user_path(@user)
      flash[:success] = "ユーザー情報を更新しました。"
    else
      render :edit
      flash[:danger] = "ユーザー情報の更新に失敗しました。記入内容を確認してください。"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.deleted_at = DateTime.now
    user.save
    if current_user.admin?
      redirect_to admin_path(current_user.id)
    else
      redirect_to user_path(user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :kana_first_name, :kana_lat_name, :nick_name, :postal_code, :address, :phone_number,:user_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="clearfix" style="margin-top: 150px; text-align: center;">
<h2 style="color: white;">ユーザー情報編集</h2>
<%= form_for @user do |f| %>
  <div class="log_in field  clearfix" style="padding: 0 34%;" >
    <ul>
      <li>
       <%= f.label :姓 ,style: "color: white;" %><br>
       <%= f.text_field :first_name, autofocus: true, autocomplete: "(姓)" %>
      </li>
      <li>
       <%= f.label :名 , style: "color: white;" %><br>
       <%= f.text_field :last_name, autofocus: true, autocomplete: "(名)" %>
      </li>
    </ul>
  </div>

  <div class="log_in field  clearfix" style="padding: 0 34%;" >
    <ul>
     <li>
       <%= f.label :"カナ(姓)",style: "color: white;"  %><br>
       <%= f.text_field :kana_first_name, autofocus: true, autocomplete: "(カナ姓)" %><br>
     </li>
     <li>
       <%= f.label :"カナ(名)",style: "color: white;"  %><br>
       <%= f.text_field :kana_last_name, autofocus: true, autocomplete: "(カナ名)" %>
     </li>
   </ul>
  </div>

  <div class="field">
    <%= f.label :ニックネーム,style: "color: white;"  %><br>
    <%= f.text_field :nick_name, autofocus: true, autocomplete: "ニックネーム" %>
  </div>

  <div class="field" style= "margin:20px 645px;">
    <%= f.attachment_field :user_image,style: "color: white;" %>
  </div>


  <div class="field">
    <%= f.label :郵便番号,style: "color: white;"  %><br>
    <%= f.text_field :postal_code, autofocus: true, autocomplete: "郵便番号" %>
  </div>

  <div class="field">
    <%= f.label :住所,style: "color: white;"  %><br>
    <%= f.text_field :address, autofocus: true, autocomplete: "住所" %>
  </div>

  <div class="field">
    <%= f.label :電話番号,style: "color: white;"  %><br>
    <%= f.text_field :phone_number, autofocus: true, autocomplete: "電話番号" %>
  </div>

  <div class="field">
    <%= f.label :email,style: "color: white;"  %><br>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="actions" style="margin-top: 25px; ">
    <%= f.submit "ユーザー情報を更新" %>
  </div>

<% end %>
</div>

app/views/users/show.html.erb
<div class="container" style="margin-top: 250px; background-color: rgba(0,0,0,0.7);">


  <div class="row">
    <div class="col-lg-4 user-main-image" >
        <%= attachment_image_tag @user, :user_image, format: 'jpeg', fallback: "/images/no_image.jpg", size: "300x300", class: "user-image" %>
        <br />
        <h1 style="background-color: rgba(255,255,255,1); border-radius: 20px; text-align:center;", class="user-nickname"><%= @user.nick_name %></h1>

     <%= link_to "ユーザ情報を編集", edit_user_path,class: "btn btn-primary user-edit" ,style: "color: black; width: 100%;" %>
     <br />
     <%=link_to "退会する", user_path(@user), "data-confirm" => "本当に退会しますか？", method: :delete, class: "btn btn-danger",style: "width:90px; margin-top: 10px;" %>
   </div>


    <div class="col-lg-8" style="color:white; width:700px;">


        <h1>行ったイベント</h1>

        <div style=" overflow: scroll; height: 400px; border: 3px solid rgba(222,6,6,0.5);">
          <% @user.asiatos.each do |f| %>
            <div class="mdia event-purchase" style="width:665px;">
              <%= link_to   event_path(f.event.id), class:"media-left" do %>
                <%= attachment_image_tag f.event, :event_image,  format: 'jpeg', fallback: "/images/alexander-popov-522100-unsplash.jpg", size: "95x95" %>
              <% end %>
              <div class="media-body">
                <div class="panel panel-default media-heading">
                  <%= link_to event_path(f.event.id), style: "color:black;" do %>
                    【<%= f.event.event_title %>】
                    <%= f.event.event_city %>〜<%= f.event.event_day.year %>年<%= f.event.event_day.month %>月<%= f.event.event_day.day %>日に開催されたイベント〜
                  <% end %>
                </div>
              </div>

            </div>
          <% end %>
        </div>









    <h2>購入履歴</h2>


    <div style=" overflow: scroll; height: 400px; border: 3px solid rgba(222,6,6,0.5);">
    <% @user.purchase_historys.order(created_at: :desc).each do |f| %>
        <% total_price = 0 %>
            <% f.purchase_items.each do |a| %>
              <div class="media " style="width:665px; ">
                <div class="media-left media-image purchase-text" >
                <%= attachment_image_tag  a, :purchase_cd_image,  format: 'jpeg', fallback: "/images/41334.jpg", size: "95x95" %>
                </div>
                <div class="media-body purchase-text">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                    <p>購入日：<%= a.purchase_history.purchase_at.year %>年<%= a.purchase_history.purchase_at.month %>月<%= a.purchase_history.purchase_at.day %>日【<%= a.purchase_cd_title %>】</p>
                  </div>
                  <div class="panel-body"></div>
                  <p style="color: black; font-size: 25px;"><%= a.purchase_cd_price %>円／購入枚数:<%= a.purchase_cd_quantity %>枚／小計<%= a.purchase_cd_quantity * a.purchase_cd_price %> 円
                    <% if a.purchase_history.send_status == "受注" %>
                      <span class="label label-default"><%= a.purchase_history.send_status %></span>
                    <% elsif a.purchase_history.send_status == "商品準備中" %>
                      <span class="label label-info"><%= a.purchase_history.send_status %></span>
                    <% else %>
                      <span class="label label-success"><%= a.purchase_history.send_status %></span>
                    <% end %>
                  </p>
                  </div>
                </div>
                <% total_price += a.purchase_cd_quantity * a.purchase_cd_price %>
            <% end %>
              </div>
        <div class="total-price-right"><h2>総計：<%= total_price %>円</h2></div>
    <% end %>
    </div>
    </div>
    </div>
    </div>
  </div>
</div>