config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :admins, only: [:show]
  resources :artists, only: [:create, :update, :destroy]
  resources :cart_items, only: [:show, :create, :destroy]
  resources :cds, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :events, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :asiatos, only: [:create, :destroy]
  end

  resources :purchase_histories, only: [:new, :create, :update]
    get  "/search" => "cds#search", as: "search"
    post "/event_search" => "events#event_search", as: "event_search"
    get "/cart_item" => "cart_items#show", as: "cart_item_buy"
    get "/admin_search" => "admins#search", as: "admin_search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	attachment :event_image
	has_many :performers, dependent: :destroy, inverse_of: :event
	has_many :artists, through: :performers
	accepts_nested_attributes_for :performers, allow_destroy: true
	has_many :comments, dependent: :destroy
	has_many :asiatos, dependent: :destroy

  has_many :users, through: :asiatos
  has_many :users, through: :comments

	geocoded_by :event_address
  before_validation :geocode


	validates :event_title, presence: true
	validates :event_day, presence: true
	validates :event_city, presence: true
	validates :event_address, presence: true

	def favorited_by?(id)
	    asiatos.where(user_id: id).exists?
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index

        if user_signed_in?
        @carts = CartItem.where(user_id: current_user.id)
        end
          if params[:events_id].nil?
            @event = Event.new
            @events = Event.page(params[:page])
          else
            @event = Event.new
            @events_array = []
            params[:events_id].each do |a|
            @events_array.push(Event.find(a))
            @events = Kaminari.paginate_array(@events_array).page(params[:page])
            @search = "true"
          end
        end
    end

    def show
        @event   = Event.find(params[:id])
        @comment = Comment.new
        if user_signed_in?
        @carts = CartItem.where(user_id: current_user.id)
        end
    end

    def edit
        @carts = CartItem.where(user_id: current_user.id)
        if user_signed_in? && current_user.admin
        @event = Event.find(params[:id])
        @artists = Artist.all
        @artist_names_id = []
        @artists.each do |ar|
            if !@artist_names_id.include?([ar.artist_name,ar.id])
            @artist_names_id.push([ar.artist_name,ar.id])
            end
        end
        else
        redirect_to events_path
        flash[:danger] = "ERROR!このページにアクセスする権限がありません。"
        end
    end

  	def create
        @event = Event.new(event_params)
        @user = User.find(current_user.id)
        if @event.save
           @event.errors.full_messages
           redirect_to event_path(@event.id)
           flash[:success] = "イベントを追加しました。"
        else
           redirect_to admin_path(@user.id)
           flash[:danger] = "ERROR!イベントの追加に失敗しました。記入内容を確認してください。"
        end
	end

    def update
        @event = Event.find(params[:id])
        if @event.update(event_params)
           redirect_to event_path(@event.id)
           flash[:success] = "イベント情報の更新に成功しました。"
        else
           redirect_to edit_event_path(@event.id)
           flash[:danger] = "ERROR!イベント情報の更新に失敗しました。記入内容を確認してください。"
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to events_path(@event)
    end



    def event_search
        event_day = params[:event][:event_day]
        event_city = params[:event][:event_city]
        @events = Event.where(event_day: event_day).where(event_city: event_city)
        events_id = []
        @events.each do |event|
        events_id.push(event.id)
        end
        redirect_to events_path(events_id: events_id)
        if events_id.blank?
           flash[:danger] = "検索結果が見つかりませんでした"
        end
    end

    private

    def event_params
        params.require(:event).permit(:event_day, :event_title, :event_image, :event_city, :event_address, performers_attributes: [:id, :artist_id, :event_id, :_destroy])
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_performer_fields.html.erb
<div class="nested-fields">
	    <%= f.label :出演アーティスト %>
	    <%= f.select :artist_id, @artist_names_id, :include_blank => true %>
    	<%= link_to_remove_association "行を削除", f, class:"btn btn-danger" %>
</div>

app/views/events/edit.html.erb
<div class="container" style="margin-top: 200px;">
	<div class="row">
		<div class="col-lg-1">
		</div>
		<div class="col-lg-10 well">
		<h2>イベント編集画面</h2>

	<%= form_for @event do |f| %>
	<div>
		<%= f.label :イベント名 %><%= f.text_field :event_title %>	
	</div>
	<div>
	    <%= f.label :開催日時 %>
		<%= f.date_field :event_day %>
	</div>
	<div>
		<%= f.label :開催場所画像 %>
	    <%= f.attachment_field :event_image, placeholder: "イメージ画像を選択" %>
	</div>
	<div>
	    <%= f.label :開催区 %>
		<%= f.select :event_city, [["渋谷","渋谷区"], ["新宿","新宿区"],["港","港区"]] %>
	</div>
	<div>
	    <%= f.fields_for :performers do |performer| %>
        <%= render 'performer_fields', f: performer %>
        <% end %>
	</div>
	<div>
	    <%= link_to_add_association '行を追加', f, :performers, class:"btn btn-info" %>
	</div>
	<div>
	    <%= f.label :MAP表示させたい位置情報の住所 %>
	    <%= f.text_field :event_address %>
	</div>
		<%= f.submit "イベントを更新", class:"btn btn-success" %>
	    <% end %>
	    <div class="col-lg-1">
	    </div>
</div>
</div>
</div>

app/views/events/index.html.erb
<div class="event_main backcolor" >
	<div id="container">
		<div id="theTarget">
			<div class="image1"></div>
			<div class="image2"></div>
			<div class="image3"></div>
			<div class="image4"></div>
			<div class="image5"></div>
		</div>
	</div>
	<div class="container">
  		<div class="row">
    		<div class="col-sm-1">
    		</div>
    		<div class="col-sm-10 main-backcolor">
				<h1 class="main-text">イベント検索</h1>
					<%=form_for @event, url: event_search_path do |f| %>
					<div class="event-search-text">
						<%= f.date_field :event_day %>
						<h4 class="search-text"><%= f.label :"区を選択" %></h4>
	  					<%= f.select :event_city, [["渋谷区", "渋谷区"], ["新宿区", "新宿区"], ["港区", "港区"]] ,class:"form-control" %>
						<div class="search-btn">
						<%= f.submit "検索する" %></div><div class="note">（※日付と区は両方選択して下さい）</div>
					</div>
					<% end %>


				<div>

					<% if @search == "true" %>
					  <h2 class="event-head"><%= @events[0].event_day.year %>年<%= @events[0].event_day.month %>月<%= @events[0].event_day.day %>日<%= @events[0].event_city %>のイベント</h2>
					<% else %>
					 <% end %>

						<% @events.each do |event| %>
						<%= link_to event_path(event.id) do %>

						<div class="event-body", style= "border: 1px solid white;">
							<div class="media">
								<div class="media-left media-image" >
								<%= attachment_image_tag event, :event_image, format: 'jpeg',fallback: "/images/alexander-popov-522100-unsplash.jpg", size: "220x220" %>
								</div>
								<div class="media-body">
									<h2 class="media-heading media-title"><%= event.event_title %></h2>
									<div class="event-text"><%= event.event_day.year %>年<%= event.event_day.month %>月<%= event.event_day.day %>日</div>
									<div class="event-text"><%= event.event_city %></div>
								</div>
							</div>
						</div>
						<% end %>
					<% end %>
					<%= paginate @events, class: "pagenate" %>
				</div>
			</div>
    		<div class="col-sm-1">
    		</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function () {
  $("#theTarget").skippr({   
      transition : 'slide',
      speed : 1000,
      easing : 'easeOutQuart',
      navType : 'block',
      childrenElementType : 'div',
      arrows : true,
      autoPlay : true,
      autoPlayDuration : 3000,
      keyboardOnAlways : true,
      hidePrevious : false
  });
});
</script>

app/views/events/show.html.erb
<div class="container" style="margin-top: 250px;  background-color: rgba(0,0,0,0.7);">

  <div class="row" style="color: white; margin-bottom:10px;">

    <div class="col-lg-12 media" >
      <div class="media-left" >
        <%= attachment_image_tag @event, :event_image, format: 'jpeg', fallback: "/images/alexander-popov-522100-unsplash.jpg" ,size: "300x300", class: "event-show-image"%>
      </div>
      <div class="media-body"  style="color: white;">
        <h1 style="color: white; padding-top: 50px; "><div class="event-show-title">【<%= @event.event_title %>】</div></br>
          <div class="event-show-text">
           <%= @event.event_day.year%>年<%= @event.event_day.month%>月<%= @event.event_day.day%>日</br>


          <% if user_signed_in? %>
          <% if @event.favorited_by?(current_user) %>
              <%= link_to  event_asiatos_path(@event), method: :delete do %>
                <%= image_tag("/images/good.png", :size => "60x60") %>

              <% end %>
              <%= @event.asiatos.count %>
              あしあと
        <% else %>
            <%= link_to  event_asiatos_path(@event), method: :post do %>
                  <%= image_tag("/images/nogood.png", :size => "60x60" ) %>

            <% end %>
            <%= @event.asiatos.count  %>
            あしあと
          </div>
         <% end %>
         <% end %>
       </h1>
     </div>
    </div>

  </div>

  <div class="row">

    <div class="col-lg-8" style="color:white; padding-left: 20px;">
      <h1 style="color: white;">出演アーティスト一覧</h1>
      <ol type="1">
      <% @event.performers.each do |f| %>

        <li style="font-size: 30px;">

            <%= link_to  search_path(id: f.artist.id),style: "color: white;" do %>
                <%= f.artist.artist_name %>
            <% end %>


        </li>
  	<% end %>
    </ol>
    </div>

    <div class="col-lg-4">
      <% if user_signed_in? && current_user.admin? %>
      <div class="row" style="color: white;">
        <div class="col-lg-12" style="text-align:center;">
          <div class="admin-show-btn">
          <%= link_to "イベント編集", edit_event_path, class: "btn btn-primary",style: "width: 110px; margin-right:  10px ; "%>


          <%=link_to "イベント削除", event_path(@event), method: :delete, "data-confirm" => "本当に削除しますか？", method: :delete, class: "btn btn-danger",style: "width: 110px; " %></div>
        </div>
      </div>
      <% end %>
      <div class="row" style="color: white;">
        <div class="col-12">
          <h5>アクセス情報</h5>
          <h5>住所：<%= @event.event_address %></h5>
          <style type="text/css">
            #map { height: 300px;
                   margin-left:auto;
                   margin-right:auto;
                   text-align:left;
                  }
          </style>


          <div id="map"></div>
        </div>
      </div>
    </div>

  </div>
  <% if user_signed_in?  %>
  <div class="row" style="width: 800px;">

      <%= form_for [@event, @comment] do |f| %>
      <div class="col-lg-12 comments">
        <h1 style="color: white; margin-left:10px;">コメント記入</h1>

        <div class="col-lg-12 comments" style=" ">
        <%= f.text_field :favorite_artist,class: "form-control " ,placeholder: "好きなアーティスト",style: "width: 200px; " %>
        <ul>
          <li><%= f.text_area :comment ,class: "form-control", placeholder: "コメントをここに", style: "width: 400px; margin-left: -50px;" %></li>
          <li><%= f.submit "送信する", class: "btn btn-lg btn-base-1", style: "margin-top: 10px;" %></li>
        </ul>
        </div>
        <% end %>

</div>
  <div class="row" >

  <div class="col-lg-12" >
    <h1 style="color:white; margin-left: 25px; ">コメント一覧</h1>
    <div style="overflow: auto; height: 200px; border: 3px solid rgba(222,6,6,0.5); width: 800px; margin-left: 27px;">
      <% @event.comments.order(created_at: :desc).each do |f| %>
        <div class="media " style="width:800px;">
          <div class="media-left">
            <%= attachment_image_tag  f.user, :user_image,  format: 'jpeg', fallback: "/images/no_image.jpg", size: "95x95" %>
          </div>
        	<div class="media-body">
            <div class="panel panel-default">
	            <div class="panel-heading">
		             好きなアーティスト：<%= f.favorite_artist %>
            	</div>
	            <div class="panel-body">
	               コメント：<%= f.comment %>
	            </div>
              </div>


        	</div>
        </div>


      	<% end %>







				</div>



   </div>
  </div>
  <% else %>
  <div class="row" >

  <div class="col-lg-12">
    <h1 style="color:white;">コメント一覧</h1>
    <div style="overflow: auto; height: 200px; border: 3px solid rgba(222,6,6,0.5); width: 800px;">
      <% @event.comments.each do |f| %>
        <div class="media " style="width:800px; ">
          <div class="media-left">
            <%= attachment_image_tag  f.user, :user_image,  format: 'jpeg', fallback: "/images/no_image.jpg", size: "95x95" %>
          </div>
        	<div class="media-body">
            <div class="panel panel-default">
	            <div class="panel-heading">
		             好きなアーティスト：<%= f.favorite_artist %>
            	</div>
	            <div class="panel-body">
	               コメント：<%= f.comment %>
	            </div>
              </div>
        	</div>
        </div>
      	<% end %>
				</div>
   </div>
  </div>
<% end %>
</div>








<script type="text/javascript">
    function initMap() {

        var test ={lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @event.event_address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=[]&callback=initMap">
</script>