config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :admins, only: [:show]
  resources :artists, only: [:create, :update, :destroy]
  resources :cart_items, only: [:show, :create, :destroy]
  resources :cds, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :events, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :asiatos, only: [:create, :destroy]
  end

  resources :purchase_histories, only: [:new, :create, :update]
    get  "/search" => "cds#search", as: "search"
    post "/event_search" => "events#event_search", as: "event_search"
    get "/cart_item" => "cart_items#show", as: "cart_item_buy"
    get "/admin_search" => "admins#search", as: "admin_search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/artist.rb
class Artist < ApplicationRecord
      has_many :musics ,inverse_of: :artist
      has_many :discs, through: :musics
	  has_many :performers
	  has_many :recoding_artists
	  has_many :cds, through: :recoding_artists
	  validates :artist_name, presence: true
end

app/models/asiato.rb
class Asiato < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cd
	belongs_to :user
end

app/models/cd.rb
class Cd < ApplicationRecord
	attachment :cd_image
	has_many :discs, inverse_of: :cd
	has_many :purchase_items
	has_many :cart_items
	has_many :recoding_artists
	has_many :artists, through: :recoding_artists
	accepts_nested_attributes_for :discs, allow_destroy: true
	accepts_nested_attributes_for :recoding_artists, allow_destroy: true
	validates :cd_title, presence: true
	validates :cd_genre, presence: true, length: { maximum:15 }
	validates :cd_label, presence: true, length: { maximum:25 }
	validates :cd_price, presence: true
	validates :cd_stock, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :event
	validates :comment, presence: true, length: { minimum:2, maximum:201 }
	validates :favorite_artist, presence: true
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :cd, inverse_of: :discs
	has_many :musics, inverse_of: :disc
    has_many :artists, through: :musics
	accepts_nested_attributes_for :musics, allow_destroy: true
	validates :disc_number, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
	attachment :event_image
	has_many :performers, dependent: :destroy, inverse_of: :event
	has_many :artists, through: :performers
	accepts_nested_attributes_for :performers, allow_destroy: true
	has_many :comments, dependent: :destroy
	has_many :asiatos, dependent: :destroy

  has_many :users, through: :asiatos
  has_many :users, through: :comments

	geocoded_by :event_address
  before_validation :geocode


	validates :event_title, presence: true
	validates :event_day, presence: true
	validates :event_city, presence: true
	validates :event_address, presence: true

	def favorited_by?(id)
	    asiatos.where(user_id: id).exists?
	end
end

app/models/music.rb
class Music < ApplicationRecord
	belongs_to :disc, inverse_of: :musics
	belongs_to :artist, inverse_of: :musics
	validates :music_title, presence: true, length: { maximum:50 }
	validates :music_number, presence: true
end

app/models/performer.rb
class Performer < ApplicationRecord
	belongs_to :artist
	belongs_to :event
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
	belongs_to :user
	has_many :purchase_items
	accepts_nested_attributes_for :purchase_items, allow_destroy: true
	validates :send_address, presence: true
	validates :send_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
	validates :send_postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "ハイフンなしの数字7桁で入力してください" }
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
	attachment :purchase_cd_image
	belongs_to :purchase_history
	belongs_to :cd
end

app/models/recoding_artist.rb
class RecodingArtist < ApplicationRecord
	belongs_to :artist
	belongs_to :cd
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attachment :user_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:trackable, :validatable

  has_many :asiatos, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :cart_items, dependent: :destroy

  has_many :purchase_historys

  has_many :events, through: :asiatos
  has_many :events, through: :comments



  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字で入力してください" }
  validates :kana_first_name, presence: true, format: { with: /\A[ァ-ンー－]+\z/, message: "全角カタカナで入力してください" }
  validates :kana_last_name, presence: true, format: { with: /\A[ァ-ンー－]+\z/, message: "全角カタカナで入力してください" }
  validates :nick_name, presence: true, length: { maximum:12 }
  validates :email, presence: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/, message: "ハイフンなしの数字7桁で入力してください" }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\zA|\A\d{11}\z/, message: "ハイフンなしの11桁で入力してください" }

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def show
    if params[:no_cd]
      @no_cds = params[:no_cd]
    end
    @carts = CartItem.where(user_id: current_user.id)
    @purchase = PurchaseHistory.new
    @cart_items = CartItem.where(user_id: current_user.id)
    @total_price = 0
    @cart_items.each do |c|
    @total_price += c.cd.cd_price * c.cd_quantity
    end
  end

  def create
  	cart_item = CartItem.new(cart_item_params)
    cart_item.user_id = current_user.id
    if CartItem.find_by(cd_id: cart_item.cd_id,user_id: current_user.id)
      redirect_to cart_item_path(current_user.id)
      flash[:danger] = "ERROR!すでに商品がカートに入っています。"
    else
      cart_item.save
      redirect_to cart_item_buy_path
      flash[:success] = "カートに商品を追加しました。"
    end
 end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_item_path(current_user.id)
    flash[:success] = "カートの商品を削除しました。"
  end



private
	def cart_item_params
		params.require(:cart_item).permit(:cd_quantity, :cd_id, :user_id)
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/asiatos_helper.rb
module AsiatosHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/show.html.erb
<div class="cartpage" style="margin-top: 200px;">
<div class="container">
	<div class="row">
		<div class="col-lg-1">

		</div>
		<div class="col-lg-10" style="background-color: rgba(0,0,0,0.7); color: white;">
			<% if @no_cds.nil? %>
			<% else %>
			<h3>在庫が切れてしまった商品</h3>
			    <% @no_cds.each do |n| %>
			    <%= n %>
			    <% end %>
			<% end %>
			<h2>カートの中身</h2>
			<div class="row">
				<% @cart_items.each do |cart| %>
				<div class="col-lg-3">
				    <%= attachment_image_tag cart.cd, :cd_image, format: 'jpeg',fallback: "/images/no_image.jpg", size: "180x180" %>
				</div>
				<div class="col-lg-9">
				    <h4>CDタイトル</h4>
				    <%= cart.cd.cd_title %>
				    <h4>値段</h4>
				    <%= cart.cd.cd_price %>円
				    <h4>購入枚数</h4>
				    <%= cart.cd_quantity %>枚
				</div>
			</div>
			<div class="row">
				　　<h3>収録曲リスト</h3>
				<div class="col-lg-12">
					<ol type="1">
				    <% cart.cd.discs.each do |d| %>
				        <% d.musics.each do |m| %>
				        <li><%= m.music_title %><%= m.artist.artist_name %></li>
				        <% end %>
				    <% end %>
				    </ol>
				</div>
				<div>
					<%= link_to "カートから削除", cart_item_path(cart.id), method: :delete, class: "btn btn-danger" %>
				</div>
			    <% end %>
		    </div>

		    <% if @cart_items.empty? %>
		     <h3>カートに商品がありません。</h3>
		     <% else %>

		    <div>
		     	<h3>総計:<%= @total_price %>円</h3>
		    </div>

		     	<input type="radio" name="btn" id="a" checked="checked">登録されている住所に送る
		     	<input type="radio" name="btn" id="b">他の住所に送る
		     <div class="text text01">
		     	<strong><%= current_user.address %></strong>に送る<br>
		     	<%= link_to "購入する",purchase_histories_path(buy1: ""), method: :post, class: "btn btn-success" %>
		     </div>
		     <div class="text text02" style="color: black; margin-top: 20px;">
		     	<%= form_for @purchase do |f| %>
		     	<p style="color :white;">送付先郵便番号</p><%= f.text_field :send_postal_code %>
		     	<p style="color :white;">送付先宛名</p><%= f.text_field :send_name %>
		     	<p style="color :white;">送付先住所</p><%= f.text_field :send_address %><br />
		     	<%= f.submit "購入する", class: "btn btn-success", style: "margin-top: 20px;" %>
		     	<% end %>
		     </div>

		     <% end %>
		</div>
		<div class="col-lg-1">

		</div>
	</div>
</div>
</div>
<script>
$(function() {
  $('[name="btn"]:radio').change( function() {
    if($('[id=a]').prop('checked')){
      $('.text').fadeOut();
      $('.text01').fadeIn();
    } else if ($('[id=b]').prop('checked')) {
      $('.text').fadeOut();
      $('.text02').fadeIn();
    }
  });
});
</script>